### ISSUE TITLE
CKURLRequest could be an operation subclass

### ISSUE THREAD

**Issue by malhal** [BennyKJohnson/OpenCloudKit#13]
It is quite normal to wrap an NSURLSession task in an operation, and would fit here since it is already attempting to implement its own cancelled and finished. I could handle this.

**Comment by BennyKJohnson** [comment]
CKWebRequest was the old class that performed the URLRequests on behalf of the task. It's now been replaced with CKURLRequest however some of the operations still use CKWebRequest. CKURLRequest still needs some work though, if you would like to work on that.

**Comment by malhal** [comment]
Sorry yeh I meant CKURLRequest

**Comment by BennyKJohnson** [comment]
I'm not in favour for this without a really good reason for doing so. It doesn't match the CloudKit Daemon implementation found [here](https://github.com/JaviSoto/iOS10-Runtime-Headers/blob/master/PrivateFrameworks/CloudKitDaemon.framework/CKDURLRequest.h)
